sonata_admin:
    title: 'Qualitrack'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

        groups:
            user:
                label: 'Users'
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

simple_things_entity_audit:
    audited_entities:
        -  App\Entity\User
